/* pantheon-files-contractor.h generated by valac 0.56.3, the Vala compiler, do not modify */

#ifndef __PLUGINS_CONTRACTOR_PANTHEON_FILES_CONTRACTOR_H__
#define __PLUGINS_CONTRACTOR_PANTHEON_FILES_CONTRACTOR_H__

#include <gtk/gtk.h>
#include <glib-object.h>
#include <granite.h>
#include <gio/gio.h>
#include "pantheon-files-core.h"
#include <glib.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define FILES_PLUGINS_TYPE_CONTRACT_MENU_ITEM (files_plugins_contract_menu_item_get_type ())
#define FILES_PLUGINS_CONTRACT_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FILES_PLUGINS_TYPE_CONTRACT_MENU_ITEM, FilesPluginsContractMenuItem))
#define FILES_PLUGINS_CONTRACT_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FILES_PLUGINS_TYPE_CONTRACT_MENU_ITEM, FilesPluginsContractMenuItemClass))
#define FILES_PLUGINS_IS_CONTRACT_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FILES_PLUGINS_TYPE_CONTRACT_MENU_ITEM))
#define FILES_PLUGINS_IS_CONTRACT_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FILES_PLUGINS_TYPE_CONTRACT_MENU_ITEM))
#define FILES_PLUGINS_CONTRACT_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FILES_PLUGINS_TYPE_CONTRACT_MENU_ITEM, FilesPluginsContractMenuItemClass))

typedef struct _FilesPluginsContractMenuItem FilesPluginsContractMenuItem;
typedef struct _FilesPluginsContractMenuItemClass FilesPluginsContractMenuItemClass;
typedef struct _FilesPluginsContractMenuItemPrivate FilesPluginsContractMenuItemPrivate;

#define FILES_PLUGINS_TYPE_CONTRACTOR (files_plugins_contractor_get_type ())
#define FILES_PLUGINS_CONTRACTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FILES_PLUGINS_TYPE_CONTRACTOR, FilesPluginsContractor))
#define FILES_PLUGINS_CONTRACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FILES_PLUGINS_TYPE_CONTRACTOR, FilesPluginsContractorClass))
#define FILES_PLUGINS_IS_CONTRACTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FILES_PLUGINS_TYPE_CONTRACTOR))
#define FILES_PLUGINS_IS_CONTRACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FILES_PLUGINS_TYPE_CONTRACTOR))
#define FILES_PLUGINS_CONTRACTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FILES_PLUGINS_TYPE_CONTRACTOR, FilesPluginsContractorClass))

typedef struct _FilesPluginsContractor FilesPluginsContractor;
typedef struct _FilesPluginsContractorClass FilesPluginsContractorClass;
typedef struct _FilesPluginsContractorPrivate FilesPluginsContractorPrivate;

struct _FilesPluginsContractMenuItem {
	GtkMenuItem parent_instance;
	FilesPluginsContractMenuItemPrivate * priv;
};

struct _FilesPluginsContractMenuItemClass {
	GtkMenuItemClass parent_class;
};

struct _FilesPluginsContractor {
	FilesPluginsBase parent_instance;
	FilesPluginsContractorPrivate * priv;
};

struct _FilesPluginsContractorClass {
	FilesPluginsBaseClass parent_class;
};

VALA_EXTERN GType files_plugins_contract_menu_item_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FilesPluginsContractMenuItem, g_object_unref)
VALA_EXTERN FilesPluginsContractMenuItem* files_plugins_contract_menu_item_new (GraniteServicesContract* contract,
                                                                    GFile** files,
                                                                    gint files_length1);
VALA_EXTERN FilesPluginsContractMenuItem* files_plugins_contract_menu_item_construct (GType object_type,
                                                                          GraniteServicesContract* contract,
                                                                          GFile** files,
                                                                          gint files_length1);
VALA_EXTERN GType files_plugins_contractor_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FilesPluginsContractor, files_plugins_base_unref)
VALA_EXTERN FilesPluginsContractor* files_plugins_contractor_new (void);
VALA_EXTERN FilesPluginsContractor* files_plugins_contractor_construct (GType object_type);
VALA_EXTERN FilesPluginsBase* module_init (void);

G_END_DECLS

#endif
