/* VolumePropertiesWindow.c generated by valac 0.56.3, the Vala compiler
 * generated from VolumePropertiesWindow.vala, do not modify */

/*
* Copyright (c) 2011 Marlin Developers (http://launchpad.net/marlin)
* Copyright (c) 2015-2018 elementary LLC <https://elementary.io>
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1335 USA.
*
* Authored by: ammonkey <am.monkeyd@gmail.com>
*/

#include <granite.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include "pantheon-files-core.h"

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define FILES_VIEW_TYPE_ABSTRACT_PROPERTIES_DIALOG (files_view_abstract_properties_dialog_get_type ())
#define FILES_VIEW_ABSTRACT_PROPERTIES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FILES_VIEW_TYPE_ABSTRACT_PROPERTIES_DIALOG, FilesViewAbstractPropertiesDialog))
#define FILES_VIEW_ABSTRACT_PROPERTIES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FILES_VIEW_TYPE_ABSTRACT_PROPERTIES_DIALOG, FilesViewAbstractPropertiesDialogClass))
#define FILES_VIEW_IS_ABSTRACT_PROPERTIES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FILES_VIEW_TYPE_ABSTRACT_PROPERTIES_DIALOG))
#define FILES_VIEW_IS_ABSTRACT_PROPERTIES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FILES_VIEW_TYPE_ABSTRACT_PROPERTIES_DIALOG))
#define FILES_VIEW_ABSTRACT_PROPERTIES_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FILES_VIEW_TYPE_ABSTRACT_PROPERTIES_DIALOG, FilesViewAbstractPropertiesDialogClass))

typedef struct _FilesViewAbstractPropertiesDialog FilesViewAbstractPropertiesDialog;
typedef struct _FilesViewAbstractPropertiesDialogClass FilesViewAbstractPropertiesDialogClass;
typedef struct _FilesViewAbstractPropertiesDialogPrivate FilesViewAbstractPropertiesDialogPrivate;

#define FILES_TYPE_STORAGE_BAR (files_storage_bar_get_type ())
#define FILES_STORAGE_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FILES_TYPE_STORAGE_BAR, FilesStorageBar))
#define FILES_STORAGE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FILES_TYPE_STORAGE_BAR, FilesStorageBarClass))
#define FILES_IS_STORAGE_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FILES_TYPE_STORAGE_BAR))
#define FILES_IS_STORAGE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FILES_TYPE_STORAGE_BAR))
#define FILES_STORAGE_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FILES_TYPE_STORAGE_BAR, FilesStorageBarClass))

typedef struct _FilesStorageBar FilesStorageBar;
typedef struct _FilesStorageBarClass FilesStorageBarClass;

#define FILES_VIEW_TYPE_VOLUME_PROPERTIES_WINDOW (files_view_volume_properties_window_get_type ())
#define FILES_VIEW_VOLUME_PROPERTIES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FILES_VIEW_TYPE_VOLUME_PROPERTIES_WINDOW, FilesViewVolumePropertiesWindow))
#define FILES_VIEW_VOLUME_PROPERTIES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FILES_VIEW_TYPE_VOLUME_PROPERTIES_WINDOW, FilesViewVolumePropertiesWindowClass))
#define FILES_VIEW_IS_VOLUME_PROPERTIES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FILES_VIEW_TYPE_VOLUME_PROPERTIES_WINDOW))
#define FILES_VIEW_IS_VOLUME_PROPERTIES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FILES_VIEW_TYPE_VOLUME_PROPERTIES_WINDOW))
#define FILES_VIEW_VOLUME_PROPERTIES_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FILES_VIEW_TYPE_VOLUME_PROPERTIES_WINDOW, FilesViewVolumePropertiesWindowClass))

typedef struct _FilesViewVolumePropertiesWindow FilesViewVolumePropertiesWindow;
typedef struct _FilesViewVolumePropertiesWindowClass FilesViewVolumePropertiesWindowClass;
typedef struct _FilesViewVolumePropertiesWindowPrivate FilesViewVolumePropertiesWindowPrivate;
enum  {
	FILES_VIEW_VOLUME_PROPERTIES_WINDOW_0_PROPERTY,
	FILES_VIEW_VOLUME_PROPERTIES_WINDOW_NUM_PROPERTIES
};
static GParamSpec* files_view_volume_properties_window_properties[FILES_VIEW_VOLUME_PROPERTIES_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_KEY_LABEL (key_label_get_type ())
#define KEY_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_KEY_LABEL, KeyLabel))
#define KEY_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_KEY_LABEL, KeyLabelClass))
#define IS_KEY_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_KEY_LABEL))
#define IS_KEY_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_KEY_LABEL))
#define KEY_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_KEY_LABEL, KeyLabelClass))

typedef struct _KeyLabel KeyLabel;
typedef struct _KeyLabelClass KeyLabelClass;

#define TYPE_VALUE_LABEL (value_label_get_type ())
#define VALUE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VALUE_LABEL, ValueLabel))
#define VALUE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VALUE_LABEL, ValueLabelClass))
#define IS_VALUE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VALUE_LABEL))
#define IS_VALUE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VALUE_LABEL))
#define VALUE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VALUE_LABEL, ValueLabelClass))

typedef struct _ValueLabel ValueLabel;
typedef struct _ValueLabelClass ValueLabelClass;
typedef enum  {
	FILES_STORAGE_BAR_ITEM_DESCRIPTION_OTHER,
	FILES_STORAGE_BAR_ITEM_DESCRIPTION_AUDIO,
	FILES_STORAGE_BAR_ITEM_DESCRIPTION_VIDEO,
	FILES_STORAGE_BAR_ITEM_DESCRIPTION_PHOTO,
	FILES_STORAGE_BAR_ITEM_DESCRIPTION_APP,
	FILES_STORAGE_BAR_ITEM_DESCRIPTION_FILES = FILES_STORAGE_BAR_ITEM_DESCRIPTION_OTHER
} FilesStorageBarItemDescription;

#define FILES_STORAGE_BAR_TYPE_ITEM_DESCRIPTION (files_storage_bar_item_description_get_type ())

struct _FilesViewAbstractPropertiesDialog {
	GraniteDialog parent_instance;
	FilesViewAbstractPropertiesDialogPrivate * priv;
	GtkGrid* info_grid;
	GtkGrid* layout;
	GtkStack* stack;
	GtkStackSwitcher* stack_switcher;
	GtkWidget* header_title;
	FilesStorageBar* storagebar;
};

struct _FilesViewAbstractPropertiesDialogClass {
	GraniteDialogClass parent_class;
};

struct _FilesViewVolumePropertiesWindow {
	FilesViewAbstractPropertiesDialog parent_instance;
	FilesViewVolumePropertiesWindowPrivate * priv;
};

struct _FilesViewVolumePropertiesWindowClass {
	FilesViewAbstractPropertiesDialogClass parent_class;
};

static gpointer files_view_volume_properties_window_parent_class = NULL;

VALA_EXTERN GType files_view_abstract_properties_dialog_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FilesViewAbstractPropertiesDialog, g_object_unref)
VALA_EXTERN GType files_storage_bar_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FilesStorageBar, g_object_unref)
VALA_EXTERN GType files_view_volume_properties_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FilesViewVolumePropertiesWindow, g_object_unref)
VALA_EXTERN FilesViewVolumePropertiesWindow* files_view_volume_properties_window_new (GMount* mount,
                                                                          GtkWindow* parent);
VALA_EXTERN FilesViewVolumePropertiesWindow* files_view_volume_properties_window_construct (GType object_type,
                                                                                GMount* mount,
                                                                                GtkWindow* parent);
VALA_EXTERN FilesViewAbstractPropertiesDialog* files_view_abstract_properties_dialog_construct (GType object_type,
                                                                                    const gchar* _title,
                                                                                    GtkWindow* parent);
VALA_EXTERN void files_view_abstract_properties_dialog_overlay_emblems (FilesViewAbstractPropertiesDialog* self,
                                                            GtkImage* file_icon,
                                                            GList* emblems_list);
static void _g_free0_ (gpointer var);
static inline void _g_list_free__g_free0_ (GList* self);
VALA_EXTERN void files_view_abstract_properties_dialog_create_header_title (FilesViewAbstractPropertiesDialog* self);
VALA_EXTERN GType key_label_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KeyLabel, g_object_unref)
VALA_EXTERN KeyLabel* key_label_new (const gchar* label);
VALA_EXTERN KeyLabel* key_label_construct (GType object_type,
                               const gchar* label);
VALA_EXTERN GType value_label_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ValueLabel, g_object_unref)
VALA_EXTERN ValueLabel* value_label_new (const gchar* label);
VALA_EXTERN ValueLabel* value_label_construct (GType object_type,
                                   const gchar* label);
VALA_EXTERN void files_view_abstract_properties_dialog_create_storage_bar (FilesViewAbstractPropertiesDialog* self,
                                                               GFileInfo* file_info,
                                                               gint line);
VALA_EXTERN GType files_storage_bar_item_description_get_type (void) G_GNUC_CONST ;
VALA_EXTERN void files_view_abstract_properties_dialog_update_storage_block_size (FilesViewAbstractPropertiesDialog* self,
                                                                      guint64 size,
                                                                      FilesStorageBarItemDescription item_description);
static GType files_view_volume_properties_window_get_type_once (void);

static void
_g_free0_ (gpointer var)
{
	var = (g_free (var), NULL);
}

static inline void
_g_list_free__g_free0_ (GList* self)
{
	g_list_free_full (self, (GDestroyNotify) _g_free0_);
}

FilesViewVolumePropertiesWindow*
files_view_volume_properties_window_construct (GType object_type,
                                               GMount* mount,
                                               GtkWindow* parent)
{
	FilesViewVolumePropertiesWindow * self = NULL;
	GFile* mount_root = NULL;
	gchar* mount_name = NULL;
	GIcon* mount_icon = NULL;
	GFileInfo* info = NULL;
	GtkImage* file_icon = NULL;
	GtkImage* _tmp12_;
	GtkImage* _tmp13_;
	GIcon* _tmp14_;
	GtkImage* _tmp15_;
	const gchar* _tmp24_;
	GtkLabel* _tmp25_ = NULL;
	KeyLabel* location_label = NULL;
	KeyLabel* _tmp26_;
	ValueLabel* location_value = NULL;
	GFile* _tmp27_;
	gchar* _tmp28_;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	gchar* _tmp34_;
	gchar* _tmp35_;
	GFile* _tmp36_;
	gchar* _tmp37_;
	gchar* _tmp38_;
	gchar* _tmp39_;
	gchar* _tmp40_;
	gchar* _tmp41_;
	gchar* _tmp42_;
	gchar* _tmp43_;
	gchar* _tmp44_;
	ValueLabel* _tmp45_;
	ValueLabel* _tmp46_;
	GtkGrid* _tmp47_;
	KeyLabel* _tmp48_;
	GtkGrid* _tmp49_;
	ValueLabel* _tmp50_;
	KeyLabel* _tmp51_;
	guint64 used_space = 0ULL;
	gboolean _tmp52_ = FALSE;
	GFileInfo* _tmp53_;
	GFileInfo* _tmp65_;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (parent != NULL, NULL);
	self = (FilesViewVolumePropertiesWindow*) files_view_abstract_properties_dialog_construct (object_type, _ ("Disk Properties"), parent);
	if (mount != NULL) {
		GFile* _tmp0_;
		gchar* _tmp1_;
		GIcon* _tmp2_;
		_tmp0_ = g_mount_get_root (mount);
		_g_object_unref0 (mount_root);
		mount_root = _tmp0_;
		_tmp1_ = g_mount_get_name (mount);
		_g_free0 (mount_name);
		mount_name = _tmp1_;
		_tmp2_ = g_mount_get_icon (mount);
		_g_object_unref0 (mount_icon);
		mount_icon = _tmp2_;
	} else {
		GFile* _tmp3_;
		gchar* _tmp4_;
		GThemedIcon* _tmp5_;
		_tmp3_ = g_file_new_for_uri ("file:///");
		_g_object_unref0 (mount_root);
		mount_root = _tmp3_;
		_tmp4_ = g_strdup (_ ("File System"));
		_g_free0 (mount_name);
		mount_name = _tmp4_;
		_tmp5_ = (GThemedIcon*) g_themed_icon_new_with_default_fallbacks (FILES_ICON_FILESYSTEM);
		_g_object_unref0 (mount_icon);
		mount_icon = (GIcon*) _tmp5_;
	}
	info = NULL;
	{
		GFileInfo* _tmp6_ = NULL;
		GFile* _tmp7_;
		GFileInfo* _tmp8_;
		GFileInfo* _tmp9_;
		_tmp7_ = mount_root;
		_tmp8_ = g_file_query_filesystem_info (_tmp7_, "filesystem::*", NULL, &_inner_error0_);
		_tmp6_ = _tmp8_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp9_ = _tmp6_;
		_tmp6_ = NULL;
		_g_object_unref0 (info);
		info = _tmp9_;
		_g_object_unref0 (_tmp6_);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp10_;
		const gchar* _tmp11_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp10_ = e;
		_tmp11_ = _tmp10_->message;
		g_warning ("VolumePropertiesWindow.vala:53: error: %s", _tmp11_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (info);
		_g_object_unref0 (mount_icon);
		_g_free0 (mount_name);
		_g_object_unref0 (mount_root);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	_tmp12_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp12_);
	file_icon = _tmp12_;
	_tmp13_ = file_icon;
	_tmp14_ = mount_icon;
	gtk_image_set_from_gicon (_tmp13_, _tmp14_, (GtkIconSize) GTK_ICON_SIZE_DIALOG);
	_tmp15_ = file_icon;
	if (_tmp15_ != NULL) {
		GList* emblems_list = NULL;
		gboolean _tmp16_ = FALSE;
		gboolean _tmp17_ = FALSE;
		GFileInfo* _tmp18_;
		GtkImage* _tmp22_;
		GList* _tmp23_;
		emblems_list = NULL;
		_tmp18_ = info;
		if (_tmp18_ != NULL) {
			GFileInfo* _tmp19_;
			_tmp19_ = info;
			_tmp17_ = g_file_info_has_attribute (_tmp19_, G_FILE_ATTRIBUTE_FILESYSTEM_READONLY);
		} else {
			_tmp17_ = FALSE;
		}
		if (_tmp17_) {
			GFileInfo* _tmp20_;
			_tmp20_ = info;
			_tmp16_ = g_file_info_get_attribute_boolean (_tmp20_, G_FILE_ATTRIBUTE_FILESYSTEM_READONLY);
		} else {
			_tmp16_ = FALSE;
		}
		if (_tmp16_) {
			gchar* _tmp21_;
			_tmp21_ = g_strdup ("emblem-readonly");
			emblems_list = g_list_append (emblems_list, _tmp21_);
		}
		_tmp22_ = file_icon;
		_tmp23_ = emblems_list;
		files_view_abstract_properties_dialog_overlay_emblems ((FilesViewAbstractPropertiesDialog*) self, _tmp22_, _tmp23_);
		(emblems_list == NULL) ? NULL : (emblems_list = (_g_list_free__g_free0_ (emblems_list), NULL));
	}
	_tmp24_ = mount_name;
	_tmp25_ = (GtkLabel*) gtk_label_new (_tmp24_);
	gtk_widget_set_halign ((GtkWidget*) _tmp25_, GTK_ALIGN_START);
	g_object_ref_sink (_tmp25_);
	_g_object_unref0 (((FilesViewAbstractPropertiesDialog*) self)->header_title);
	((FilesViewAbstractPropertiesDialog*) self)->header_title = (GtkWidget*) _tmp25_;
	files_view_abstract_properties_dialog_create_header_title ((FilesViewAbstractPropertiesDialog*) self);
	_tmp26_ = key_label_new (_ ("Location:"));
	g_object_ref_sink (_tmp26_);
	location_label = _tmp26_;
	_tmp27_ = mount_root;
	_tmp28_ = g_file_get_uri (_tmp27_);
	_tmp29_ = _tmp28_;
	_tmp30_ = g_markup_escape_text (_tmp29_, (gssize) -1);
	_tmp31_ = _tmp30_;
	_tmp32_ = g_strconcat ("<a href=\"", _tmp31_, NULL);
	_tmp33_ = _tmp32_;
	_tmp34_ = g_strconcat (_tmp33_, "\">", NULL);
	_tmp35_ = _tmp34_;
	_tmp36_ = mount_root;
	_tmp37_ = g_file_get_parse_name (_tmp36_);
	_tmp38_ = _tmp37_;
	_tmp39_ = g_markup_escape_text (_tmp38_, (gssize) -1);
	_tmp40_ = _tmp39_;
	_tmp41_ = g_strconcat (_tmp35_, _tmp40_, NULL);
	_tmp42_ = _tmp41_;
	_tmp43_ = g_strconcat (_tmp42_, "</a>", NULL);
	_tmp44_ = _tmp43_;
	_tmp45_ = value_label_new (_tmp44_);
	g_object_ref_sink (_tmp45_);
	_tmp46_ = _tmp45_;
	_g_free0 (_tmp44_);
	_g_free0 (_tmp42_);
	_g_free0 (_tmp40_);
	_g_free0 (_tmp38_);
	_g_free0 (_tmp35_);
	_g_free0 (_tmp33_);
	_g_free0 (_tmp31_);
	_g_free0 (_tmp29_);
	location_value = _tmp46_;
	_tmp47_ = ((FilesViewAbstractPropertiesDialog*) self)->info_grid;
	_tmp48_ = location_label;
	gtk_grid_attach (_tmp47_, (GtkWidget*) _tmp48_, 0, 1, 1, 1);
	_tmp49_ = ((FilesViewAbstractPropertiesDialog*) self)->info_grid;
	_tmp50_ = location_value;
	_tmp51_ = location_label;
	gtk_grid_attach_next_to (_tmp49_, (GtkWidget*) _tmp50_, (GtkWidget*) _tmp51_, GTK_POS_RIGHT, 1, 1);
	used_space = (guint64) 0;
	_tmp53_ = info;
	if (_tmp53_ != NULL) {
		GFileInfo* _tmp54_;
		_tmp54_ = info;
		_tmp52_ = g_file_info_has_attribute (_tmp54_, G_FILE_ATTRIBUTE_FILESYSTEM_TYPE);
	} else {
		_tmp52_ = FALSE;
	}
	if (_tmp52_) {
		KeyLabel* key_label = NULL;
		KeyLabel* _tmp55_;
		ValueLabel* value_label = NULL;
		GFileInfo* _tmp56_;
		const gchar* _tmp57_;
		ValueLabel* _tmp58_;
		GtkGrid* _tmp59_;
		KeyLabel* _tmp60_;
		GtkGrid* _tmp61_;
		ValueLabel* _tmp62_;
		KeyLabel* _tmp63_;
		GFileInfo* _tmp64_;
		_tmp55_ = key_label_new (_ ("Format:"));
		g_object_ref_sink (_tmp55_);
		key_label = _tmp55_;
		_tmp56_ = info;
		_tmp57_ = g_file_info_get_attribute_string (_tmp56_, G_FILE_ATTRIBUTE_FILESYSTEM_TYPE);
		_tmp58_ = value_label_new (_tmp57_);
		g_object_ref_sink (_tmp58_);
		value_label = _tmp58_;
		_tmp59_ = ((FilesViewAbstractPropertiesDialog*) self)->info_grid;
		_tmp60_ = key_label;
		gtk_grid_attach (_tmp59_, (GtkWidget*) _tmp60_, 0, 2, 1, 1);
		_tmp61_ = ((FilesViewAbstractPropertiesDialog*) self)->info_grid;
		_tmp62_ = value_label;
		_tmp63_ = key_label;
		gtk_grid_attach_next_to (_tmp61_, (GtkWidget*) _tmp62_, (GtkWidget*) _tmp63_, GTK_POS_RIGHT, 1, 1);
		_tmp64_ = info;
		used_space = g_file_info_get_attribute_uint64 (_tmp64_, G_FILE_ATTRIBUTE_FILESYSTEM_USED);
		_g_object_unref0 (value_label);
		_g_object_unref0 (key_label);
	}
	_tmp65_ = info;
	files_view_abstract_properties_dialog_create_storage_bar ((FilesViewAbstractPropertiesDialog*) self, _tmp65_, 3);
	files_view_abstract_properties_dialog_update_storage_block_size ((FilesViewAbstractPropertiesDialog*) self, used_space, FILES_STORAGE_BAR_ITEM_DESCRIPTION_FILES);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (location_value);
	_g_object_unref0 (location_label);
	_g_object_unref0 (file_icon);
	_g_object_unref0 (info);
	_g_object_unref0 (mount_icon);
	_g_free0 (mount_name);
	_g_object_unref0 (mount_root);
	return self;
}

FilesViewVolumePropertiesWindow*
files_view_volume_properties_window_new (GMount* mount,
                                         GtkWindow* parent)
{
	return files_view_volume_properties_window_construct (FILES_VIEW_TYPE_VOLUME_PROPERTIES_WINDOW, mount, parent);
}

static void
files_view_volume_properties_window_class_init (FilesViewVolumePropertiesWindowClass * klass,
                                                gpointer klass_data)
{
	files_view_volume_properties_window_parent_class = g_type_class_peek_parent (klass);
}

static void
files_view_volume_properties_window_instance_init (FilesViewVolumePropertiesWindow * self,
                                                   gpointer klass)
{
}

static GType
files_view_volume_properties_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (FilesViewVolumePropertiesWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) files_view_volume_properties_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FilesViewVolumePropertiesWindow), 0, (GInstanceInitFunc) files_view_volume_properties_window_instance_init, NULL };
	GType files_view_volume_properties_window_type_id;
	files_view_volume_properties_window_type_id = g_type_register_static (FILES_VIEW_TYPE_ABSTRACT_PROPERTIES_DIALOG, "FilesViewVolumePropertiesWindow", &g_define_type_info, 0);
	return files_view_volume_properties_window_type_id;
}

GType
files_view_volume_properties_window_get_type (void)
{
	static volatile gsize files_view_volume_properties_window_type_id__once = 0;
	if (g_once_init_enter (&files_view_volume_properties_window_type_id__once)) {
		GType files_view_volume_properties_window_type_id;
		files_view_volume_properties_window_type_id = files_view_volume_properties_window_get_type_once ();
		g_once_init_leave (&files_view_volume_properties_window_type_id__once, files_view_volume_properties_window_type_id);
	}
	return files_view_volume_properties_window_type_id__once;
}

