/* ButtonWithMenu.c generated by valac 0.56.3, the Vala compiler
 * generated from ButtonWithMenu.vala, do not modify */

#include "pantheon-files-core.h"
#include <gtk/gtk.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib-object.h>
#include <gdk/gdk.h>

enum  {
	FILES_VIEW_CHROME_BUTTON_WITH_MENU_0_PROPERTY,
	FILES_VIEW_CHROME_BUTTON_WITH_MENU_HORIZONTAL_MENU_POSITION_PROPERTY,
	FILES_VIEW_CHROME_BUTTON_WITH_MENU_VERTICAL_MENU_POSITION_PROPERTY,
	FILES_VIEW_CHROME_BUTTON_WITH_MENU_MENU_PROPERTY,
	FILES_VIEW_CHROME_BUTTON_WITH_MENU_NUM_PROPERTIES
};
static GParamSpec* files_view_chrome_button_with_menu_properties[FILES_VIEW_CHROME_BUTTON_WITH_MENU_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_GdkEventButton_free0(var) ((var == NULL) ? NULL : (var = (_vala_GdkEventButton_free (var), NULL)))
typedef struct _Block41Data Block41Data;
enum  {
	FILES_VIEW_CHROME_BUTTON_WITH_MENU_RIGHT_CLICK_SIGNAL,
	FILES_VIEW_CHROME_BUTTON_WITH_MENU_SLOW_PRESS_SIGNAL,
	FILES_VIEW_CHROME_BUTTON_WITH_MENU_NUM_SIGNALS
};
static guint files_view_chrome_button_with_menu_signals[FILES_VIEW_CHROME_BUTTON_WITH_MENU_NUM_SIGNALS] = {0};

struct _FilesViewChromeButtonWithMenuPrivate {
	FilesViewChromeButtonWithMenuHMenuPosition _horizontal_menu_position;
	FilesViewChromeButtonWithMenuVMenuPosition _vertical_menu_position;
	GtkMenu* _menu;
	gint long_press_time;
	guint timeout;
	guint last_click_time;
};

struct _Block41Data {
	int _ref_count_;
	FilesViewChromeButtonWithMenu* self;
	GdkEventButton* ev;
};

static gint FilesViewChromeButtonWithMenu_private_offset;
static gpointer files_view_chrome_button_with_menu_parent_class = NULL;

static void files_view_chrome_button_with_menu_update_menu_properties (FilesViewChromeButtonWithMenu* self);
static void __lambda67_ (FilesViewChromeButtonWithMenu* self);
static void files_view_chrome_button_with_menu_deactivate_menu (FilesViewChromeButtonWithMenu* self);
static void ___lambda67__gtk_menu_shell_deactivate (GtkMenuShell* _sender,
                                             gpointer self);
static void _files_view_chrome_button_with_menu_popdown_menu_gtk_menu_shell_deactivate (GtkMenuShell* _sender,
                                                                                 gpointer self);
static gboolean files_view_chrome_button_with_menu_on_mnemonic_activate (FilesViewChromeButtonWithMenu* self,
                                                                  gboolean group_cycling);
static gboolean _files_view_chrome_button_with_menu_on_mnemonic_activate_gtk_widget_mnemonic_activate (GtkWidget* _sender,
                                                                                                gboolean group_cycling,
                                                                                                gpointer self);
static gboolean files_view_chrome_button_with_menu_on_button_press_event (FilesViewChromeButtonWithMenu* self,
                                                                   GdkEventButton* ev);
static gboolean _files_view_chrome_button_with_menu_on_button_press_event_gtk_widget_button_press_event (GtkWidget* _sender,
                                                                                                  GdkEventButton* event,
                                                                                                  gpointer self);
static gboolean files_view_chrome_button_with_menu_on_button_release_event (FilesViewChromeButtonWithMenu* self,
                                                                     GdkEventButton* ev);
static gboolean _files_view_chrome_button_with_menu_on_button_release_event_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                                      GdkEventButton* event,
                                                                                                      gpointer self);
static gboolean __lambda69_ (FilesViewChromeButtonWithMenu* self);
static gboolean ___lambda69__gtk_widget_motion_notify_event (GtkWidget* _sender,
                                                      GdkEventMotion* event,
                                                      gpointer self);
static void files_view_chrome_button_with_menu_real_show_all (GtkWidget* base);
static GdkEventButton* _vala_GdkEventButton_copy (GdkEventButton* self);
static void _vala_GdkEventButton_free (GdkEventButton* self);
static Block41Data* block41_data_ref (Block41Data* _data41_);
static void block41_data_unref (void * _userdata_);
static gboolean ___lambda68_ (Block41Data* _data41_);
static gboolean ____lambda68__gsource_func (gpointer self);
static GObject * files_view_chrome_button_with_menu_constructor (GType type,
                                                          guint n_construct_properties,
                                                          GObjectConstructParam * construct_properties);
static void _files_view_chrome_button_with_menu___lambda70_ (FilesViewChromeButtonWithMenu* self);
static gboolean __lambda71_ (FilesViewChromeButtonWithMenu* self);
static gboolean ___lambda71__gtk_widget_configure_event (GtkWidget* _sender,
                                                  GdkEventConfigure* event,
                                                  gpointer self);
static void __files_view_chrome_button_with_menu___lambda70__gtk_widget_realize (GtkWidget* _sender,
                                                                          gpointer self);
static void files_view_chrome_button_with_menu_finalize (GObject * obj);
static GType files_view_chrome_button_with_menu_get_type_once (void);
static void _vala_files_view_chrome_button_with_menu_get_property (GObject * object,
                                                            guint property_id,
                                                            GValue * value,
                                                            GParamSpec * pspec);
static void _vala_files_view_chrome_button_with_menu_set_property (GObject * object,
                                                            guint property_id,
                                                            const GValue * value,
                                                            GParamSpec * pspec);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

static inline gpointer
files_view_chrome_button_with_menu_get_instance_private (FilesViewChromeButtonWithMenu* self)
{
	return G_STRUCT_MEMBER_P (self, FilesViewChromeButtonWithMenu_private_offset);
}

/**
         * VMenuPosition:
         */
static GType
files_view_chrome_button_with_menu_vmenu_position_get_type_once (void)
{
	static const GEnumValue values[] = {{FILES_VIEW_CHROME_BUTTON_WITH_MENU_VMENU_POSITION_TOP, "FILES_VIEW_CHROME_BUTTON_WITH_MENU_VMENU_POSITION_TOP", "top"}, {FILES_VIEW_CHROME_BUTTON_WITH_MENU_VMENU_POSITION_BOTTOM, "FILES_VIEW_CHROME_BUTTON_WITH_MENU_VMENU_POSITION_BOTTOM", "bottom"}, {0, NULL, NULL}};
	GType files_view_chrome_button_with_menu_vmenu_position_type_id;
	files_view_chrome_button_with_menu_vmenu_position_type_id = g_enum_register_static ("FilesViewChromeButtonWithMenuVMenuPosition", values);
	return files_view_chrome_button_with_menu_vmenu_position_type_id;
}

GType
files_view_chrome_button_with_menu_vmenu_position_get_type (void)
{
	static volatile gsize files_view_chrome_button_with_menu_vmenu_position_type_id__once = 0;
	if (g_once_init_enter (&files_view_chrome_button_with_menu_vmenu_position_type_id__once)) {
		GType files_view_chrome_button_with_menu_vmenu_position_type_id;
		files_view_chrome_button_with_menu_vmenu_position_type_id = files_view_chrome_button_with_menu_vmenu_position_get_type_once ();
		g_once_init_leave (&files_view_chrome_button_with_menu_vmenu_position_type_id__once, files_view_chrome_button_with_menu_vmenu_position_type_id);
	}
	return files_view_chrome_button_with_menu_vmenu_position_type_id__once;
}

/**
         * HMenuPosition:
         */
static GType
files_view_chrome_button_with_menu_hmenu_position_get_type_once (void)
{
	static const GEnumValue values[] = {{FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_LEFT, "FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_LEFT", "left"}, {FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_CENTER, "FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_CENTER", "center"}, {FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_RIGHT, "FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_RIGHT", "right"}, {FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_INSIDE_WINDOW, "FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_INSIDE_WINDOW", "inside-window"}, {0, NULL, NULL}};
	GType files_view_chrome_button_with_menu_hmenu_position_type_id;
	files_view_chrome_button_with_menu_hmenu_position_type_id = g_enum_register_static ("FilesViewChromeButtonWithMenuHMenuPosition", values);
	return files_view_chrome_button_with_menu_hmenu_position_type_id;
}

GType
files_view_chrome_button_with_menu_hmenu_position_get_type (void)
{
	static volatile gsize files_view_chrome_button_with_menu_hmenu_position_type_id__once = 0;
	if (g_once_init_enter (&files_view_chrome_button_with_menu_hmenu_position_type_id__once)) {
		GType files_view_chrome_button_with_menu_hmenu_position_type_id;
		files_view_chrome_button_with_menu_hmenu_position_type_id = files_view_chrome_button_with_menu_hmenu_position_get_type_once ();
		g_once_init_leave (&files_view_chrome_button_with_menu_hmenu_position_type_id__once, files_view_chrome_button_with_menu_hmenu_position_type_id);
	}
	return files_view_chrome_button_with_menu_hmenu_position_type_id__once;
}

FilesViewChromeButtonWithMenu*
files_view_chrome_button_with_menu_construct_from_icon_name (GType object_type,
                                                             const gchar* icon_name,
                                                             GtkIconSize size)
{
	FilesViewChromeButtonWithMenu * self = NULL;
	GtkImage* _tmp0_;
	GtkImage* _tmp1_;
	g_return_val_if_fail (icon_name != NULL, NULL);
	self = (FilesViewChromeButtonWithMenu*) files_view_chrome_button_with_menu_construct (object_type);
	_tmp0_ = (GtkImage*) gtk_image_new_from_icon_name (icon_name, (GtkIconSize) size);
	g_object_ref_sink (_tmp0_);
	_tmp1_ = _tmp0_;
	gtk_button_set_image ((GtkButton*) self, (GtkWidget*) _tmp1_);
	_g_object_unref0 (_tmp1_);
	return self;
}

FilesViewChromeButtonWithMenu*
files_view_chrome_button_with_menu_new_from_icon_name (const gchar* icon_name,
                                                       GtkIconSize size)
{
	return files_view_chrome_button_with_menu_construct_from_icon_name (FILES_VIEW_CHROME_TYPE_BUTTON_WITH_MENU, icon_name, size);
}

static void
__lambda67_ (FilesViewChromeButtonWithMenu* self)
{
	files_view_chrome_button_with_menu_deactivate_menu (self);
}

static void
___lambda67__gtk_menu_shell_deactivate (GtkMenuShell* _sender,
                                        gpointer self)
{
	__lambda67_ ((FilesViewChromeButtonWithMenu*) self);
}

static void
_files_view_chrome_button_with_menu_popdown_menu_gtk_menu_shell_deactivate (GtkMenuShell* _sender,
                                                                            gpointer self)
{
	files_view_chrome_button_with_menu_popdown_menu ((FilesViewChromeButtonWithMenu*) self);
}

static void
files_view_chrome_button_with_menu_update_menu_properties (FilesViewChromeButtonWithMenu* self)
{
	GtkMenu* _tmp0_;
	GtkMenu* _tmp1_;
	GtkMenu* _tmp2_;
	GtkMenu* _tmp3_;
	GtkMenu* _tmp4_;
	GtkMenu* _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = files_view_chrome_button_with_menu_get_menu (self);
	_tmp1_ = _tmp0_;
	gtk_menu_attach_to_widget (_tmp1_, (GtkWidget*) self, NULL);
	_tmp2_ = files_view_chrome_button_with_menu_get_menu (self);
	_tmp3_ = _tmp2_;
	g_signal_connect_object ((GtkMenuShell*) _tmp3_, "deactivate", (GCallback) ___lambda67__gtk_menu_shell_deactivate, self, 0);
	_tmp4_ = files_view_chrome_button_with_menu_get_menu (self);
	_tmp5_ = _tmp4_;
	g_signal_connect_object ((GtkMenuShell*) _tmp5_, "deactivate", (GCallback) _files_view_chrome_button_with_menu_popdown_menu_gtk_menu_shell_deactivate, self, 0);
}

static gboolean
_files_view_chrome_button_with_menu_on_mnemonic_activate_gtk_widget_mnemonic_activate (GtkWidget* _sender,
                                                                                       gboolean group_cycling,
                                                                                       gpointer self)
{
	gboolean result;
	result = files_view_chrome_button_with_menu_on_mnemonic_activate ((FilesViewChromeButtonWithMenu*) self, group_cycling);
	return result;
}

static gboolean
_files_view_chrome_button_with_menu_on_button_press_event_gtk_widget_button_press_event (GtkWidget* _sender,
                                                                                         GdkEventButton* event,
                                                                                         gpointer self)
{
	gboolean result;
	result = files_view_chrome_button_with_menu_on_button_press_event ((FilesViewChromeButtonWithMenu*) self, event);
	return result;
}

static gboolean
_files_view_chrome_button_with_menu_on_button_release_event_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                             GdkEventButton* event,
                                                                                             gpointer self)
{
	gboolean result;
	result = files_view_chrome_button_with_menu_on_button_release_event ((FilesViewChromeButtonWithMenu*) self, event);
	return result;
}

static gboolean
__lambda69_ (FilesViewChromeButtonWithMenu* self)
{
	gboolean result;
	if (self->priv->timeout > ((guint) 0)) {
		g_source_remove (self->priv->timeout);
		self->priv->timeout = (guint) 0;
		gtk_toggle_button_set_active ((GtkToggleButton*) self, FALSE);
	}
	result = GDK_EVENT_PROPAGATE;
	return result;
}

static gboolean
___lambda69__gtk_widget_motion_notify_event (GtkWidget* _sender,
                                             GdkEventMotion* event,
                                             gpointer self)
{
	gboolean result;
	result = __lambda69_ ((FilesViewChromeButtonWithMenu*) self);
	return result;
}

FilesViewChromeButtonWithMenu*
files_view_chrome_button_with_menu_construct (GType object_type)
{
	FilesViewChromeButtonWithMenu * self = NULL;
	GtkMenu* _tmp0_;
	GtkMenu* _tmp1_;
	GdkEventMask _tmp2_;
	GdkEventMask _tmp3_;
	self = (FilesViewChromeButtonWithMenu*) g_object_new (object_type, NULL);
	gtk_button_set_use_underline ((GtkButton*) self, TRUE);
	gtk_widget_set_can_focus ((GtkWidget*) self, TRUE);
	_tmp0_ = (GtkMenu*) gtk_menu_new ();
	g_object_ref_sink (_tmp0_);
	_tmp1_ = _tmp0_;
	files_view_chrome_button_with_menu_set_menu (self, _tmp1_);
	_g_object_unref0 (_tmp1_);
	g_signal_connect_object ((GtkWidget*) self, "mnemonic-activate", (GCallback) _files_view_chrome_button_with_menu_on_mnemonic_activate_gtk_widget_mnemonic_activate, self, 0);
	_tmp2_ = gtk_widget_get_events ((GtkWidget*) self);
	_tmp3_ = _tmp2_;
	gtk_widget_set_events ((GtkWidget*) self, _tmp3_ | ((GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK) | GDK_BUTTON_MOTION_MASK));
	g_signal_connect_object ((GtkWidget*) self, "button-press-event", (GCallback) _files_view_chrome_button_with_menu_on_button_press_event_gtk_widget_button_press_event, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "button-release-event", (GCallback) _files_view_chrome_button_with_menu_on_button_release_event_gtk_widget_button_release_event, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "motion-notify-event", (GCallback) ___lambda69__gtk_widget_motion_notify_event, self, 0);
	return self;
}

FilesViewChromeButtonWithMenu*
files_view_chrome_button_with_menu_new (void)
{
	return files_view_chrome_button_with_menu_construct (FILES_VIEW_CHROME_TYPE_BUTTON_WITH_MENU);
}

static void
files_view_chrome_button_with_menu_real_show_all (GtkWidget* base)
{
	FilesViewChromeButtonWithMenu * self;
	GtkMenu* _tmp0_;
	GtkMenu* _tmp1_;
	self = (FilesViewChromeButtonWithMenu*) base;
	_tmp0_ = files_view_chrome_button_with_menu_get_menu (self);
	_tmp1_ = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) _tmp1_);
	GTK_WIDGET_CLASS (files_view_chrome_button_with_menu_parent_class)->show_all ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_toggle_button_get_type (), GtkToggleButton));
}

static void
files_view_chrome_button_with_menu_deactivate_menu (FilesViewChromeButtonWithMenu* self)
{
	g_return_if_fail (self != NULL);
	gtk_toggle_button_set_active ((GtkToggleButton*) self, FALSE);
}

static gboolean
files_view_chrome_button_with_menu_on_button_release_event (FilesViewChromeButtonWithMenu* self,
                                                            GdkEventButton* ev)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (ev != NULL, FALSE);
	if ((ev->time - self->priv->last_click_time) < ((guint32) self->priv->long_press_time)) {
		g_signal_emit (self, files_view_chrome_button_with_menu_signals[FILES_VIEW_CHROME_BUTTON_WITH_MENU_SLOW_PRESS_SIGNAL], 0);
		gtk_toggle_button_set_active ((GtkToggleButton*) self, FALSE);
	}
	if (self->priv->timeout > ((guint) 0)) {
		g_source_remove (self->priv->timeout);
		self->priv->timeout = (guint) 0;
	}
	result = FALSE;
	return result;
}

static GdkEventButton*
_vala_GdkEventButton_copy (GdkEventButton* self)
{
	return g_boxed_copy (gdk_event_get_type (), self);
}

static gpointer
__vala_GdkEventButton_copy0 (gpointer self)
{
	return self ? _vala_GdkEventButton_copy (self) : NULL;
}

static void
_vala_GdkEventButton_free (GdkEventButton* self)
{
	g_boxed_free (gdk_event_get_type (), self);
}

static Block41Data*
block41_data_ref (Block41Data* _data41_)
{
	g_atomic_int_inc (&_data41_->_ref_count_);
	return _data41_;
}

static void
block41_data_unref (void * _userdata_)
{
	Block41Data* _data41_;
	_data41_ = (Block41Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data41_->_ref_count_)) {
		FilesViewChromeButtonWithMenu* self;
		self = _data41_->self;
		__vala_GdkEventButton_free0 (_data41_->ev);
		_g_object_unref0 (self);
		g_slice_free (Block41Data, _data41_);
	}
}

static gboolean
___lambda68_ (Block41Data* _data41_)
{
	FilesViewChromeButtonWithMenu* self;
	gboolean result;
	self = _data41_->self;
	self->priv->timeout = (guint) 0;
	files_view_chrome_button_with_menu_popup_menu (self, _data41_->ev);
	result = G_SOURCE_REMOVE;
	return result;
}

static gboolean
____lambda68__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda68_ (self);
	return result;
}

static gboolean
files_view_chrome_button_with_menu_on_button_press_event (FilesViewChromeButtonWithMenu* self,
                                                          GdkEventButton* ev)
{
	Block41Data* _data41_;
	GdkEventButton* _tmp0_;
	gint max_press_time = 0;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (ev != NULL, FALSE);
	_data41_ = g_slice_new0 (Block41Data);
	_data41_->_ref_count_ = 1;
	_data41_->self = g_object_ref (self);
	_tmp0_ = __vala_GdkEventButton_copy0 (ev);
	__vala_GdkEventButton_free0 (_data41_->ev);
	_data41_->ev = _tmp0_;
	max_press_time = self->priv->long_press_time;
	if (_data41_->ev->button == ((guint) 1)) {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = _data41_->ev->button == ((guint) 3);
	}
	if (_tmp1_) {
		gtk_toggle_button_set_active ((GtkToggleButton*) self, TRUE);
	}
	if (self->priv->timeout == ((guint) 0)) {
		_tmp2_ = _data41_->ev->button == ((guint) 1);
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		self->priv->last_click_time = (guint) _data41_->ev->time;
		self->priv->timeout = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) max_press_time, ____lambda68__gsource_func, block41_data_ref (_data41_), block41_data_unref);
	}
	if (_data41_->ev->button == ((guint) 3)) {
		g_signal_emit (self, files_view_chrome_button_with_menu_signals[FILES_VIEW_CHROME_BUTTON_WITH_MENU_RIGHT_CLICK_SIGNAL], 0, _data41_->ev);
		files_view_chrome_button_with_menu_popup_menu (self, _data41_->ev);
	}
	result = TRUE;
	block41_data_unref (_data41_);
	_data41_ = NULL;
	return result;
}

static gboolean
files_view_chrome_button_with_menu_on_mnemonic_activate (FilesViewChromeButtonWithMenu* self,
                                                         gboolean group_cycling)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	if (!group_cycling) {
		g_signal_emit_by_name ((GtkButton*) self, "activate");
	} else {
		gboolean _tmp0_;
		gboolean _tmp1_;
		_tmp0_ = gtk_widget_get_can_focus ((GtkWidget*) self);
		_tmp1_ = _tmp0_;
		if (_tmp1_) {
			gtk_widget_grab_focus ((GtkWidget*) self);
		}
	}
	result = TRUE;
	return result;
}

void
files_view_chrome_button_with_menu_popup_menu (FilesViewChromeButtonWithMenu* self,
                                               GdkEventButton* ev)
{
	GtkMenu* _tmp0_;
	GtkMenu* _tmp1_;
	GtkMenu* _tmp2_;
	GtkMenu* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = files_view_chrome_button_with_menu_get_menu (self);
	_tmp1_ = _tmp0_;
	gtk_menu_popup_at_widget (_tmp1_, (GtkWidget*) self, GDK_GRAVITY_SOUTH_WEST, GDK_GRAVITY_NORTH_WEST, (GdkEvent*) ev);
	_tmp2_ = files_view_chrome_button_with_menu_get_menu (self);
	_tmp3_ = _tmp2_;
	gtk_menu_shell_select_first ((GtkMenuShell*) _tmp3_, FALSE);
}

void
files_view_chrome_button_with_menu_popdown_menu (FilesViewChromeButtonWithMenu* self)
{
	GtkMenu* _tmp0_;
	GtkMenu* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = files_view_chrome_button_with_menu_get_menu (self);
	_tmp1_ = _tmp0_;
	gtk_menu_popdown (_tmp1_);
}

FilesViewChromeButtonWithMenuHMenuPosition
files_view_chrome_button_with_menu_get_horizontal_menu_position (FilesViewChromeButtonWithMenu* self)
{
	FilesViewChromeButtonWithMenuHMenuPosition result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_horizontal_menu_position;
	return result;
}

void
files_view_chrome_button_with_menu_set_horizontal_menu_position (FilesViewChromeButtonWithMenu* self,
                                                                 FilesViewChromeButtonWithMenuHMenuPosition value)
{
	FilesViewChromeButtonWithMenuHMenuPosition old_value;
	g_return_if_fail (self != NULL);
	old_value = files_view_chrome_button_with_menu_get_horizontal_menu_position (self);
	if (old_value != value) {
		self->priv->_horizontal_menu_position = value;
		g_object_notify_by_pspec ((GObject *) self, files_view_chrome_button_with_menu_properties[FILES_VIEW_CHROME_BUTTON_WITH_MENU_HORIZONTAL_MENU_POSITION_PROPERTY]);
	}
}

FilesViewChromeButtonWithMenuVMenuPosition
files_view_chrome_button_with_menu_get_vertical_menu_position (FilesViewChromeButtonWithMenu* self)
{
	FilesViewChromeButtonWithMenuVMenuPosition result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_vertical_menu_position;
	return result;
}

void
files_view_chrome_button_with_menu_set_vertical_menu_position (FilesViewChromeButtonWithMenu* self,
                                                               FilesViewChromeButtonWithMenuVMenuPosition value)
{
	FilesViewChromeButtonWithMenuVMenuPosition old_value;
	g_return_if_fail (self != NULL);
	old_value = files_view_chrome_button_with_menu_get_vertical_menu_position (self);
	if (old_value != value) {
		self->priv->_vertical_menu_position = value;
		g_object_notify_by_pspec ((GObject *) self, files_view_chrome_button_with_menu_properties[FILES_VIEW_CHROME_BUTTON_WITH_MENU_VERTICAL_MENU_POSITION_PROPERTY]);
	}
}

GtkMenu*
files_view_chrome_button_with_menu_get_menu (FilesViewChromeButtonWithMenu* self)
{
	GtkMenu* result;
	GtkMenu* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_menu;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
files_view_chrome_button_with_menu_set_menu (FilesViewChromeButtonWithMenu* self,
                                             GtkMenu* value)
{
	GtkMenu* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _g_object_ref0 (value);
	_g_object_unref0 (self->priv->_menu);
	self->priv->_menu = _tmp0_;
	files_view_chrome_button_with_menu_update_menu_properties (self);
	g_object_notify_by_pspec ((GObject *) self, files_view_chrome_button_with_menu_properties[FILES_VIEW_CHROME_BUTTON_WITH_MENU_MENU_PROPERTY]);
}

static gboolean
__lambda71_ (FilesViewChromeButtonWithMenu* self)
{
	gboolean result;
	if (self->priv->timeout > ((guint) 0)) {
		g_source_remove (self->priv->timeout);
		self->priv->timeout = (guint) 0;
	}
	result = FALSE;
	return result;
}

static gboolean
___lambda71__gtk_widget_configure_event (GtkWidget* _sender,
                                         GdkEventConfigure* event,
                                         gpointer self)
{
	gboolean result;
	result = __lambda71_ ((FilesViewChromeButtonWithMenu*) self);
	return result;
}

static void
_files_view_chrome_button_with_menu___lambda70_ (FilesViewChromeButtonWithMenu* self)
{
	GtkWidget* _tmp0_;
	_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self);
	g_signal_connect_object (_tmp0_, "configure-event", (GCallback) ___lambda71__gtk_widget_configure_event, self, 0);
}

static void
__files_view_chrome_button_with_menu___lambda70__gtk_widget_realize (GtkWidget* _sender,
                                                                     gpointer self)
{
	_files_view_chrome_button_with_menu___lambda70_ ((FilesViewChromeButtonWithMenu*) self);
}

static GObject *
files_view_chrome_button_with_menu_constructor (GType type,
                                                guint n_construct_properties,
                                                GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	FilesViewChromeButtonWithMenu * self;
	parent_class = G_OBJECT_CLASS (files_view_chrome_button_with_menu_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FILES_VIEW_CHROME_TYPE_BUTTON_WITH_MENU, FilesViewChromeButtonWithMenu);
	self->priv->timeout = (guint) 0;
	g_signal_connect_object ((GtkWidget*) self, "realize", (GCallback) __files_view_chrome_button_with_menu___lambda70__gtk_widget_realize, self, 0);
	return obj;
}

static void
files_view_chrome_button_with_menu_class_init (FilesViewChromeButtonWithMenuClass * klass,
                                               gpointer klass_data)
{
	files_view_chrome_button_with_menu_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &FilesViewChromeButtonWithMenu_private_offset);
	((GtkWidgetClass *) klass)->show_all = (void (*) (GtkWidget*)) files_view_chrome_button_with_menu_real_show_all;
	G_OBJECT_CLASS (klass)->get_property = _vala_files_view_chrome_button_with_menu_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_files_view_chrome_button_with_menu_set_property;
	G_OBJECT_CLASS (klass)->constructor = files_view_chrome_button_with_menu_constructor;
	G_OBJECT_CLASS (klass)->finalize = files_view_chrome_button_with_menu_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), FILES_VIEW_CHROME_BUTTON_WITH_MENU_HORIZONTAL_MENU_POSITION_PROPERTY, files_view_chrome_button_with_menu_properties[FILES_VIEW_CHROME_BUTTON_WITH_MENU_HORIZONTAL_MENU_POSITION_PROPERTY] = g_param_spec_enum ("horizontal-menu-position", "horizontal-menu-position", "horizontal-menu-position", FILES_VIEW_CHROME_BUTTON_WITH_MENU_TYPE_HMENU_POSITION, FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_CENTER, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FILES_VIEW_CHROME_BUTTON_WITH_MENU_VERTICAL_MENU_POSITION_PROPERTY, files_view_chrome_button_with_menu_properties[FILES_VIEW_CHROME_BUTTON_WITH_MENU_VERTICAL_MENU_POSITION_PROPERTY] = g_param_spec_enum ("vertical-menu-position", "vertical-menu-position", "vertical-menu-position", FILES_VIEW_CHROME_BUTTON_WITH_MENU_TYPE_VMENU_POSITION, FILES_VIEW_CHROME_BUTTON_WITH_MENU_VMENU_POSITION_BOTTOM, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FILES_VIEW_CHROME_BUTTON_WITH_MENU_MENU_PROPERTY, files_view_chrome_button_with_menu_properties[FILES_VIEW_CHROME_BUTTON_WITH_MENU_MENU_PROPERTY] = g_param_spec_object ("menu", "menu", "menu", gtk_menu_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	files_view_chrome_button_with_menu_signals[FILES_VIEW_CHROME_BUTTON_WITH_MENU_RIGHT_CLICK_SIGNAL] = g_signal_new ("right-click", FILES_VIEW_CHROME_TYPE_BUTTON_WITH_MENU, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOXED, G_TYPE_NONE, 1, gdk_event_get_type ());
	files_view_chrome_button_with_menu_signals[FILES_VIEW_CHROME_BUTTON_WITH_MENU_SLOW_PRESS_SIGNAL] = g_signal_new ("slow-press", FILES_VIEW_CHROME_TYPE_BUTTON_WITH_MENU, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}

static void
files_view_chrome_button_with_menu_instance_init (FilesViewChromeButtonWithMenu * self,
                                                  gpointer klass)
{
	GtkSettings* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	self->priv = files_view_chrome_button_with_menu_get_instance_private (self);
	self->priv->_horizontal_menu_position = FILES_VIEW_CHROME_BUTTON_WITH_MENU_HMENU_POSITION_CENTER;
	self->priv->_vertical_menu_position = FILES_VIEW_CHROME_BUTTON_WITH_MENU_VMENU_POSITION_BOTTOM;
	_tmp0_ = gtk_settings_get_default ();
	g_object_get (_tmp0_, "gtk-double-click-time", &_tmp1_, NULL);
	_tmp2_ = _tmp1_;
	self->priv->long_press_time = _tmp2_ * 2;
	self->priv->timeout = (guint) 0;
	self->priv->last_click_time = (guint) 0;
}

static void
files_view_chrome_button_with_menu_finalize (GObject * obj)
{
	FilesViewChromeButtonWithMenu * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FILES_VIEW_CHROME_TYPE_BUTTON_WITH_MENU, FilesViewChromeButtonWithMenu);
	_g_object_unref0 (self->priv->_menu);
	G_OBJECT_CLASS (files_view_chrome_button_with_menu_parent_class)->finalize (obj);
}

/**
     * ButtonWithMenu
     * - support long click / right click with depressed button states
     * - activate a GtkAction if any or popup a menu
     * (used in history navigation buttons and the AppMenu)
     */
static GType
files_view_chrome_button_with_menu_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (FilesViewChromeButtonWithMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) files_view_chrome_button_with_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FilesViewChromeButtonWithMenu), 0, (GInstanceInitFunc) files_view_chrome_button_with_menu_instance_init, NULL };
	GType files_view_chrome_button_with_menu_type_id;
	files_view_chrome_button_with_menu_type_id = g_type_register_static (gtk_toggle_button_get_type (), "FilesViewChromeButtonWithMenu", &g_define_type_info, 0);
	FilesViewChromeButtonWithMenu_private_offset = g_type_add_instance_private (files_view_chrome_button_with_menu_type_id, sizeof (FilesViewChromeButtonWithMenuPrivate));
	return files_view_chrome_button_with_menu_type_id;
}

GType
files_view_chrome_button_with_menu_get_type (void)
{
	static volatile gsize files_view_chrome_button_with_menu_type_id__once = 0;
	if (g_once_init_enter (&files_view_chrome_button_with_menu_type_id__once)) {
		GType files_view_chrome_button_with_menu_type_id;
		files_view_chrome_button_with_menu_type_id = files_view_chrome_button_with_menu_get_type_once ();
		g_once_init_leave (&files_view_chrome_button_with_menu_type_id__once, files_view_chrome_button_with_menu_type_id);
	}
	return files_view_chrome_button_with_menu_type_id__once;
}

static void
_vala_files_view_chrome_button_with_menu_get_property (GObject * object,
                                                       guint property_id,
                                                       GValue * value,
                                                       GParamSpec * pspec)
{
	FilesViewChromeButtonWithMenu * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FILES_VIEW_CHROME_TYPE_BUTTON_WITH_MENU, FilesViewChromeButtonWithMenu);
	switch (property_id) {
		case FILES_VIEW_CHROME_BUTTON_WITH_MENU_HORIZONTAL_MENU_POSITION_PROPERTY:
		g_value_set_enum (value, files_view_chrome_button_with_menu_get_horizontal_menu_position (self));
		break;
		case FILES_VIEW_CHROME_BUTTON_WITH_MENU_VERTICAL_MENU_POSITION_PROPERTY:
		g_value_set_enum (value, files_view_chrome_button_with_menu_get_vertical_menu_position (self));
		break;
		case FILES_VIEW_CHROME_BUTTON_WITH_MENU_MENU_PROPERTY:
		g_value_set_object (value, files_view_chrome_button_with_menu_get_menu (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_files_view_chrome_button_with_menu_set_property (GObject * object,
                                                       guint property_id,
                                                       const GValue * value,
                                                       GParamSpec * pspec)
{
	FilesViewChromeButtonWithMenu * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FILES_VIEW_CHROME_TYPE_BUTTON_WITH_MENU, FilesViewChromeButtonWithMenu);
	switch (property_id) {
		case FILES_VIEW_CHROME_BUTTON_WITH_MENU_HORIZONTAL_MENU_POSITION_PROPERTY:
		files_view_chrome_button_with_menu_set_horizontal_menu_position (self, g_value_get_enum (value));
		break;
		case FILES_VIEW_CHROME_BUTTON_WITH_MENU_VERTICAL_MENU_POSITION_PROPERTY:
		files_view_chrome_button_with_menu_set_vertical_menu_position (self, g_value_get_enum (value));
		break;
		case FILES_VIEW_CHROME_BUTTON_WITH_MENU_MENU_PROPERTY:
		files_view_chrome_button_with_menu_set_menu (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

